/**
 * 公式符号数据（对照 latexLive 的分类与分组整理）
 * - sym：普通符号，按钮图形就是符号本身
 * - tpl：带空位的结构，按钮图形用 □ 占位（空括号渲染出来是空白）
 * 校验：pnpm check:symbols 会逐个渲染，KaTeX 认不出来的会被报出来
 */

export interface SymbolItem {
  /** 点下去插入的 LaTeX 代码 */
  latex: string
  /** 按钮上画出来的图形 */
  face: string
  /** 中文名（鼠标提示） */
  label: string
}

export interface SymbolSection {
  title: string
  items: SymbolItem[]
}

export interface SymbolCategory {
  key: string
  label: string
  sections: SymbolSection[]
}

const sym = (label: string, latex: string): SymbolItem => ({ label, latex, face: latex })
const tpl = (label: string, latex: string): SymbolItem => ({
  label,
  latex,
  face: latex.replace(/\{\}/g, '{\\Box}'),
})

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    key: 'common',
    label: '常用符号',
    sections: [
      {
        title: '二元运算符 Binary operations',
        items: [
          sym('加', '+'),
          sym('减', '-'),
          sym('乘', '\\times'),
          sym('除', '\\div'),
          sym('加减', '\\pm'),
          sym('减加', '\\mp'),
          sym('点', '\\cdot'),
          sym('星', '\\ast'),
          sym('星号', '\\star'),
          sym('圆圈', '\\circ'),
          sym('实心点', '\\bullet'),
          sym('圈加', '\\oplus'),
          sym('圈减', '\\ominus'),
          sym('圈乘', '\\otimes'),
          sym('圈斜杠', '\\oslash'),
          sym('圈点', '\\odot'),
          sym('圈圈', '\\circledcirc'),
          sym('并集', '\\cup'),
          sym('交集', '\\cap'),
          sym('大方并', '\\bigcup'),
          sym('大方交', '\\bigcap'),
          sym('方形并', '\\sqcup'),
          sym('方形交', '\\sqcap'),
          sym('余积', '\\amalg'),
          sym('集合差', '\\setminus'),
          sym('大圆圈', '\\bigcirc'),
          sym('大圈加', '\\bigoplus'),
          sym('大圈乘', '\\bigotimes'),
          sym('圈积', '\\wr'),
          sym('方框加', '\\boxplus'),
          sym('方框减', '\\boxminus'),
          sym('方框乘', '\\boxtimes'),
          sym('方框点', '\\boxdot'),
          sym('菱形运算符', '\\diamond'),
          sym('上三角', '\\triangle'),
          sym('下三角', '\\triangledown'),
          sym('左三角乘', '\\ltimes'),
          sym('右三角乘', '\\rtimes'),
          sym('蝴蝶结', '\\bowtie'),
          sym('连接关系', '\\Join'),
        ],
      },
      {
        title: '二元关系符 Binary relations',
        items: [
          sym('小于', '<'),
          sym('大于', '>'),
          sym('等于', '='),
          sym('小于等于', '\\le'),
          sym('大于等于', '\\ge'),
          sym('不等于', '\\ne'),
          sym('恒等于', '\\equiv'),
          sym('约等于', '\\approx'),
          sym('渐近等于', '\\simeq'),
          sym('全等', '\\cong'),
          sym('相似', '\\sim'),
          sym('点等号', '\\doteq'),
          sym('渐近等价', '\\asymp'),
          sym('远小于', '\\ll'),
          sym('远大于', '\\gg'),
          sym('先于', '\\prec'),
          sym('后于', '\\succ'),
          sym('先于等于', '\\preceq'),
          sym('后于等于', '\\succeq'),
          sym('正比于', '\\propto'),
          sym('真子集', '\\subset'),
          sym('真超集', '\\supset'),
          sym('子集或等于', '\\subseteq'),
          sym('超集或等于', '\\supseteq'),
          sym('方形子集', '\\sqsubset'),
          sym('方形超集', '\\sqsupset'),
          sym('属于', '\\in'),
          sym('不属于', '\\notin'),
          sym('包含元素', '\\ni'),
          sym('不包含', '\\not\\ni'),
          sym('平行', '\\parallel'),
          sym('垂直', '\\perp'),
          sym('整除', '\\mid'),
          sym('不整除', '\\nmid'),
          sym('满足', '\\models'),
          sym('推出', '\\vdash'),
          sym('反推出', '\\dashv'),
          sym('上弧关系', '\\smile'),
          sym('下弧关系', '\\frown'),
          sym('小于不小于', '\\nless'),
          sym('大于不大于', '\\ngtr'),
          sym('小于等于否', '\\nleq'),
          sym('大于等于否', '\\ngeq'),
        ],
      },
      {
        title: '箭头符号 Arrows',
        items: [
          sym('左箭头', '\\leftarrow'),
          sym('右箭头', '\\rightarrow'),
          sym('上箭头', '\\uparrow'),
          sym('下箭头', '\\downarrow'),
          sym('左右箭头', '\\leftrightarrow'),
          sym('双线上箭头', '\\Uparrow'),
          sym('双线下箭头', '\\Downarrow'),
          sym('双线左右箭头', '\\Leftrightarrow'),
          sym('双线左箭头', '\\Leftarrow'),
          sym('双线右箭头', '\\Rightarrow'),
          sym('长左箭头', '\\longleftarrow'),
          sym('长右箭头', '\\longrightarrow'),
          sym('长左右箭头', '\\longleftrightarrow'),
          sym('长双线左箭头', '\\Longleftarrow'),
          sym('长双线右箭头', '\\Longrightarrow'),
          sym('长双线左右箭头', '\\Longleftrightarrow'),
          sym('映射到', '\\mapsto'),
          sym('长映射到', '\\longmapsto'),
          sym('钩右箭头', '\\hookrightarrow'),
          sym('钩左箭头', '\\hookleftarrow'),
          sym('东北箭头', '\\nearrow'),
          sym('东南箭头', '\\searrow'),
          sym('西南箭头', '\\swarrow'),
          sym('西北箭头', '\\nwarrow'),
          sym('右半箭头', '\\rightharpoonup'),
          sym('左半箭头', '\\leftharpoonup'),
          sym('向右上箭头', '\\rightleftharpoons'),
          sym('左右半箭头', '\\leftrightharpoons'),
          sym('上弧右箭头', '\\curvearrowright'),
          sym('上弧左箭头', '\\curvearrowleft'),
          sym('循环箭头', '\\circlearrowright'),
          sym('长等号右箭头', '\\Longrightarrow'),
          sym('右箭头带竖线', '\\mapsto'),
        ],
      },
      {
        title: '其他符号 Others',
        items: [
          sym('任意', '\\forall'),
          sym('存在', '\\exists'),
          sym('不存在', '\\nexists'),
          sym('逻辑非', '\\neg'),
          sym('逻辑或', '\\lor'),
          sym('逻辑与', '\\land'),
          sym('空集', '\\varnothing'),
          sym('无穷大', '\\infty'),
          sym('劈形算符', '\\nabla'),
          sym('偏导符号', '\\partial'),
          sym('因为', '\\because'),
          sym('所以', '\\therefore'),
          sym('省略号', '\\cdots'),
          sym('居中省略号', '\\cdots'),
          sym('竖向省略号', '\\vdots'),
          sym('斜向省略号', '\\ddots'),
          sym('三角形', '\\triangle'),
          sym('方框', '\\square'),
          sym('菱形', '\\lozenge'),
          sym('角', '\\angle'),
          sym('测量角', '\\measuredangle'),
          sym('球面角', '\\sphericalangle'),
          sym('顶符号', '\\top'),
          sym('底符号', '\\bot'),
          sym('度数', '^{\\circ}'),
          sym('根号', '\\surd'),
          sym('撇号', "'"),
          sym('剑号', '\\dagger'),
          sym('双剑号', '\\ddagger'),
          sym('章节符号', '\\S'),
          sym('段落符号', '\\P'),
          sym('百分号', '\\%'),
          // 注意：KaTeX 不支持 \permil，而且**不报错**——会静默渲染成 "permil" 六个字母。
          // \text{‰} 才能画出真正的千分号（控制台有字符度量警告，不影响显示）
          sym('千分号', '\\text{‰}'),
          sym('方块花色', '\\spadesuit'),
          sym('红心花色', '\\heartsuit'),
          sym('梅花花色', '\\clubsuit'),
          sym('黑桃花色', '\\diamondsuit'),
          sym('降号', '\\flat'),
          sym('还原号', '\\natural'),
          sym('升号', '\\sharp'),
        ],
      },
    ],
  },
  {
    key: 'greek',
    label: '希腊字母',
    sections: [
      {
        title: '小写 Lowercase',
        items: [
          sym('阿尔法 α', '\\alpha'),
          sym('贝塔 β', '\\beta'),
          sym('伽马 γ', '\\gamma'),
          sym('德尔塔 δ', '\\delta'),
          sym('艾普西龙 ε', '\\varepsilon'),
          sym('伊普西龙 ϵ', '\\epsilon'),
          sym('泽塔 ζ', '\\zeta'),
          sym('伊塔 η', '\\eta'),
          sym('西塔 θ', '\\theta'),
          sym('西塔变体 ϑ', '\\vartheta'),
          sym('约塔 ι', '\\iota'),
          sym('卡帕 κ', '\\kappa'),
          sym('兰姆达 λ', '\\lambda'),
          sym('缪 μ', '\\mu'),
          sym('纽 ν', '\\nu'),
          sym('克西 ξ', '\\xi'),
          sym('奥密克戎 ο', 'o'),
          sym('派 π', '\\pi'),
          sym('派变体 ϖ', '\\varpi'),
          sym('柔 ρ', '\\rho'),
          sym('柔变体 ϱ', '\\varrho'),
          sym('西格玛 σ', '\\sigma'),
          sym('西格玛尾 ς', '\\varsigma'),
          sym('陶 τ', '\\tau'),
          sym('宇普西龙 υ', '\\upsilon'),
          sym('斐 φ', '\\varphi'),
          sym('斐变体 ϕ', '\\phi'),
          sym('卡伊 χ', '\\chi'),
          sym('普西 ψ', '\\psi'),
          sym('欧米伽 ω', '\\omega'),
        ],
      },
      {
        title: '大写 Uppercase',
        items: [
          sym('伽马 Γ', '\\Gamma'),
          sym('德尔塔 Δ', '\\Delta'),
          sym('西塔 Θ', '\\Theta'),
          sym('兰姆达 Λ', '\\Lambda'),
          sym('克西 Ξ', '\\Xi'),
          sym('派 Π', '\\Pi'),
          sym('西格玛 Σ', '\\Sigma'),
          sym('宇普西龙 Υ', '\\Upsilon'),
          sym('斐 Φ', '\\Phi'),
          sym('普西 Ψ', '\\Psi'),
          sym('欧米伽 Ω', '\\Omega'),
        ],
      },
      {
        title: '其他 Others',
        items: [
          sym('约化普朗克常数 ℏ', '\\hbar'),
          sym('手写 l ℓ', '\\ell'),
          sym('虚部 ℑ', '\\Im'),
          sym('实部 ℜ', '\\Re'),
          sym('魏尔斯特拉斯 p ℘', '\\wp'),
          sym('倒欧姆 ℧', '\\mho'),
          sym('偏导 ∂', '\\partial'),
          sym('补集 ∁', '\\complement'),
          sym('黑板粗体 A', '\\mathbb{A}'),
          sym('黑板粗体 B', '\\mathbb{B}'),
          sym('黑板粗体 C', '\\mathbb{C}'),
          sym('黑板粗体 H', '\\mathbb{H}'),
          sym('黑板粗体 N', '\\mathbb{N}'),
          sym('黑板粗体 Q', '\\mathbb{Q}'),
          sym('黑板粗体 R', '\\mathbb{R}'),
          sym('黑板粗体 Z', '\\mathbb{Z}'),
          sym('手写体 A', '\\mathcal{A}'),
          sym('手写体 B', '\\mathcal{B}'),
          sym('手写体 C', '\\mathcal{C}'),
          sym('手写体 F', '\\mathcal{F}'),
          sym('手写体 L', '\\mathcal{L}'),
          sym('德文尖角体 A', '\\mathfrak{A}'),
          sym('德文尖角体 B', '\\mathfrak{B}'),
          sym('德文尖角体 C', '\\mathfrak{C}'),
        ],
      },
    ],
  },
  {
    key: 'fraction',
    label: '分数微分',
    sections: [
      {
        title: '分数 Fractions',
        items: [
          tpl('分数', '\\frac{}{}'),
          tpl('大号分数', '\\dfrac{}{}'),
          tpl('小号分数', '\\tfrac{}{}'),
          {
            label: '连分数',
            latex: '\\cfrac{1}{1+\\cfrac{1}{1+\\cfrac{1}{1}}}',
            // 按钮上只画两层，避免按钮被撑得过高
            face: '\\cfrac{1}{1+\\cfrac{1}{1}}',
          },
          tpl('分式 a/b', '\\frac{a}{b}'),
          tpl('带根号分式', '\\frac{\\sqrt{a}}{b}'),
        ],
      },
      {
        title: '导数 Derivative',
        items: [
          tpl('微分 dx', '\\mathrm{d}x'),
          tpl('微分 dt', '\\mathrm{d}t'),
          tpl('偏微分 ∂x', '\\partial x'),
          tpl('偏微分 ∂t', '\\partial t'),
          tpl('偏微分 ∂y/∂x', '\\frac{\\partial y}{\\partial x}'),
          tpl('二阶偏导', '\\frac{\\partial^2 y}{\\partial x_1 \\partial x_2}'),
          sym('Nabla 算子', '\\nabla'),
          sym('一阶导数 f′', "f'"),
          sym('二阶导数 f″', "f''"),
          tpl('n 阶导数', 'f^{(n)}'),
          sym('一阶导点 ȧ', '\\dot{a}'),
          sym('二阶导点 ä', '\\ddot{a}'),
          tpl('导数 dy/dx', '\\frac{\\mathrm{d}y}{\\mathrm{d}x}'),
          tpl('二阶导 d²y/dx²', '\\frac{\\mathrm{d}^2 y}{\\mathrm{d}x^2}'),
          tpl('n 阶导', '\\frac{\\mathrm{d}^n y}{\\mathrm{d}x^n}'),
        ],
      },
      {
        title: '模算术 Modular arithmetic',
        items: [
          tpl('模除 a mod b', 'a \\bmod b'),
          tpl('同余 a ≡ b (mod m)', 'a \\equiv b \\pmod{m}'),
          tpl('最大公约数', '\\gcd(m, n)'),
          tpl('最小公倍数', '\\operatorname{lcm}(m, n)'),
        ],
      },
    ],
  },
  {
    key: 'radical',
    label: '根式角标',
    sections: [
      {
        title: '根式 Radicals',
        items: [
          tpl('开平方 √x', '\\sqrt{}'),
          tpl('开 n 次方', '\\sqrt[n]{}'),
        ],
      },
      {
        title: '上下标 Sub&Super',
        items: [
          tpl('上标', '^{}'),
          tpl('下标', '_{}'),
          tpl('混合上下标', '_{}^{}'),
          tpl('左侧上下标', '{}_{}^{}'),
          tpl('x 的 a 次方', 'x^{a}'),
          tpl('x 的下标 a', 'x_{a}'),
          tpl('上下标组合', 'x_{a}^{b}'),
          tpl('上下标嵌套', 'x_{i}^{y^{4}_{3}}'),
        ],
      },
      {
        title: '重音符及其他 Accents and Others',
        items: [
          tpl('帽子重音', '\\hat{}'),
          tpl('反尖音重音', '\\check{}'),
          tpl('抑音符', '\\grave{}'),
          tpl('锐音符', '\\acute{}'),
          tpl('波浪重音', '\\tilde{}'),
          tpl('短音符', '\\breve{}'),
          tpl('短横重音', '\\bar{}'),
          tpl('上点', '\\dot{}'),
          tpl('双点', '\\ddot{}'),
          tpl('圆圈重音', '\\mathring{}'),
          tpl('向量箭头', '\\vec{}'),
          tpl('否定斜线', '\\not{}'),
          tpl('度数符号', '37^{\\circ}'),
          tpl('宽波浪线', '\\widetilde{abc}'),
          tpl('宽帽子重音', '\\widehat{abc}'),
          tpl('上划线', '\\overline{abc}'),
          tpl('下划线', '\\underline{abc}'),
          tpl('上方弧线', '\\overset{\\frown}{AB}'),
          tpl('下方弧线', '\\underset{\\frown}{AB}'),
          tpl('上花括号', '\\overbrace{abc}'),
          tpl('下花括号', '\\underbrace{abc}'),
          tpl('上方右箭头', '\\overrightarrow{AB}'),
          tpl('上方左箭头', '\\overleftarrow{AB}'),
          tpl('上方双向箭头', '\\overleftrightarrow{AB}'),
        ],
      },
    ],
  },
  {
    key: 'limits',
    label: '极限对数',
    sections: [
      {
        title: '极限 Limits',
        items: [
          tpl('极限 lim', '\\lim_{}'),
          tpl('lim x→a', '\\lim_{x \\to a}'),
          tpl('lim x→0', '\\lim_{x \\to 0}'),
          tpl('lim x→∞', '\\lim_{x \\to \\infty}'),
          tpl('lim x→0+', '\\lim_{x \\to 0^{+}}'),
          tpl('最大值 max', '\\max_{}'),
          tpl('最小值 min', '\\min_{}'),
        ],
      },
      {
        title: '对数指数 Logarithms and exponentials',
        items: [
          tpl('对数 log_a b', '\\log_{a} b'),
          tpl('常用对数 lg', '\\lg_{a} b'),
          tpl('自然对数 ln', '\\ln_{a} b'),
          tpl('指数 exp', '\\exp a'),
          tpl('幂 a^n', 'a^{n}'),
          tpl('根号指数 e^x', 'e^{x}'),
        ],
      },
      {
        title: '界限 Bounds',
        items: [
          tpl('最小值 min x', '\\min x'),
          tpl('最大值 max y', '\\max y'),
          tpl('上确界 sup', '\\sup t'),
          tpl('下确界 inf', '\\inf s'),
          tpl('lim u', '\\lim u'),
          tpl('上极限 lim sup', '\\limsup v'),
          tpl('下极限 lim inf', '\\liminf v'),
          tpl('维度 dim', '\\dim p'),
          tpl('核 ker', '\\ker \\varphi'),
        ],
      },
    ],
  },
  {
    key: 'trig',
    label: '三角函数',
    sections: [
      {
        title: '三角函数 Trigonometric functions',
        items: [
          tpl('正弦 sin α', '\\sin \\alpha'),
          tpl('余弦 cos α', '\\cos \\alpha'),
          tpl('正切 tan α', '\\tan \\alpha'),
          tpl('余切 cot α', '\\cot \\alpha'),
          tpl('正割 sec α', '\\sec \\alpha'),
          tpl('余割 csc α', '\\csc \\alpha'),
        ],
      },
      {
        title: '反三角函数 Inverse trigonometric functions',
        items: [
          tpl('反正弦 sin⁻¹', '\\sin^{-1} \\alpha'),
          tpl('反余弦 cos⁻¹', '\\cos^{-1} \\alpha'),
          tpl('反正切 tan⁻¹', '\\tan^{-1} \\alpha'),
          tpl('反余切 cot⁻¹', '\\cot^{-1} \\alpha'),
          tpl('反正割 sec⁻¹', '\\sec^{-1} \\alpha'),
          tpl('反余割 csc⁻¹', '\\csc^{-1} \\alpha'),
          tpl('arcsin', '\\arcsin a'),
          tpl('arccos', '\\arccos a'),
          tpl('arctan', '\\arctan a'),
          tpl('arccot', '\\operatorname{arccot} a'),
          tpl('arcsec', '\\operatorname{arcsec} a'),
          tpl('arccsc', '\\operatorname{arccsc} a'),
        ],
      },
      {
        title: '双曲函数 Hyperbolic functions',
        items: [
          tpl('双曲正弦 sinh', '\\sinh \\alpha'),
          tpl('双曲余弦 cosh', '\\cosh \\alpha'),
          tpl('双曲正切 tanh', '\\tanh \\alpha'),
          tpl('双曲余切 coth', '\\coth \\alpha'),
          tpl('双曲正割 sech', '\\operatorname{sech} \\alpha'),
          tpl('双曲余割 csch', '\\operatorname{csch} \\alpha'),
        ],
      },
      {
        title: '反双曲函数 Inverse hyperbolic functions',
        items: [
          tpl('反双曲正弦', '\\sinh^{-1} \\alpha'),
          tpl('反双曲余弦', '\\cosh^{-1} \\alpha'),
          tpl('反双曲正切', '\\tanh^{-1} \\alpha'),
          tpl('反双曲余切', '\\coth^{-1} \\alpha'),
          tpl('反双曲正割', '\\operatorname{sech}^{-1} \\alpha'),
          tpl('反双曲余割', '\\operatorname{csch}^{-1} \\alpha'),
        ],
      },
    ],
  },
  {
    key: 'integral',
    label: '积分运算',
    sections: [
      {
        title: '积分 Integral',
        items: [
          sym('积分 ∫', '\\int'),
          tpl('定积分 ∫ᵃᵇ', '\\int_{a}^{b}'),
          tpl('积分带函数', '\\int f(x)\\,\\mathrm{d}x'),
        ],
      },
      {
        title: '双重积分 Double integral',
        items: [
          sym('双重积分 ∬', '\\iint'),
          tpl('双重定积分', '\\iint_{a}^{b}'),
          tpl('双重积分带函数', '\\iint f(x, y)\\,\\mathrm{d}x\\,\\mathrm{d}y'),
        ],
      },
      {
        title: '三重积分 Triple integral',
        items: [
          sym('三重积分 ∭', '\\iiint'),
          tpl('三重定积分', '\\iiint_{a}^{b}'),
          tpl('三重积分带函数', '\\iiint f(x, y, z)\\,\\mathrm{d}V'),
        ],
      },
      {
        title: '曲线积分 Closed line or path integral',
        items: [
          sym('环路积分 ∮', '\\oint'),
          tpl('环路积分带路径', '\\oint_{C}'),
        ],
      },
    ],
  },
  {
    key: 'bigop',
    label: '大型运算',
    sections: [
      {
        title: '求和 Summation',
        items: [
          sym('求和 ∑', '\\sum'),
          tpl('求和带上限', '\\sum_{a}^{b}'),
          tpl('求和带下标', '\\sum_{i=1}^{n}'),
        ],
      },
      {
        title: '乘积余积 Product and coproduct',
        items: [
          sym('乘积 ∏', '\\prod'),
          tpl('乘积带上限', '\\prod_{a}^{b}'),
          sym('余积 ∐', '\\coprod'),
          tpl('余积带上限', '\\coprod_{a}^{b}'),
        ],
      },
      {
        title: '并集交集 Union and intersection',
        items: [
          sym('并集 ∪', '\\cup'),
          tpl('并集带上限', '\\bigcup_{a}^{b}'),
          sym('大方并 ⋃', '\\bigcup'),
          sym('交集 ∩', '\\cap'),
          tpl('交集带下限', '\\bigcap_{a}^{b}'),
          sym('大方交 ⋂', '\\bigcap'),
        ],
      },
      {
        title: '析取合取 Disjunction and conjunction',
        items: [
          sym('析取 ∨', '\\vee'),
          tpl('析取带上限', '\\bigvee_{a}^{b}'),
          sym('大析取 ⋁', '\\bigvee'),
          sym('合取 ∧', '\\wedge'),
          tpl('合取带下限', '\\bigwedge_{a}^{b}'),
          sym('大合取 ⋀', '\\bigwedge'),
        ],
      },
    ],
  },
  {
    key: 'bracket',
    label: '括号取整',
    sections: [
      {
        title: '括号 Brackets',
        items: [
          tpl('圆括号', '\\left(\\right)'),
          tpl('方括号', '\\left[\\right]'),
          tpl('尖括号', '\\left\\langle\\right\\rangle'),
          tpl('花括号', '\\left\\{\\right\\}'),
          tpl('单竖线', '\\left|\\right|'),
          tpl('双竖线', '\\left\\|\\right\\|'),
          tpl('下取整', '\\left\\lfloor\\right\\rfloor'),
          tpl('上取整', '\\left\\lceil\\right\\rceil'),
        ],
      },
      {
        title: '常用 Commons',
        items: [
          tpl('组合数', '\\binom{}{}'),
          tpl('左开右闭区间', '\\left[0,1\\right)'),
          sym('左矢 ⟨ψ|', '\\langle\\psi|'),
          sym('右矢 |ψ⟩', '|\\psi\\rangle'),
          sym('内积 ⟨ψ|ψ⟩', '\\langle\\psi|\\psi\\rangle'),
        ],
      },
    ],
  },
  {
    key: 'matrix',
    label: '数组矩阵',
    sections: [
      {
        title: '矩阵与多行结构 Matrices',
        items: [
          tpl('矩阵', '\\begin{matrix}a&b\\\\c&d\\end{matrix}'),
          tpl('方括号矩阵', '\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}'),
          tpl('圆括号矩阵', '\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}'),
          tpl('单竖线矩阵', '\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}'),
          tpl('双竖线矩阵', '\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}'),
          tpl('花括号矩阵', '\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}'),
          tpl('小矩阵', '\\begin{smallmatrix}a&b\\\\c&d\\end{smallmatrix}'),
          tpl('条件等式', '\\begin{cases}a,&x>0\\\\b,&x\\le 0\\end{cases}'),
          tpl('多行对齐等式', '\\begin{aligned}a&=b\\\\c&=d\\end{aligned}'),
          tpl('居中多行', '\\begin{gathered}a=b\\\\c=d\\end{gathered}'),
          tpl('数组', '\\begin{array}{cc}a&b\\\\c&d\\end{array}'),
        ],
      },
    ],
  },
]
